name: ✨ Feature request
description: Sugerir uma nova funcionalidade ou melhoria
title: "feat: "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema / contexto
      description: Que dor esta feature resolve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução proposta
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas
